// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { application } from '../libs/stimulus'


import CkeditorController from './ckeditor_controller'
application.register('ckeditor', CkeditorController)

import FieldsController from './fields_controller'
application.register('fields', FieldsController)

import FilepondController from './filepond_controller'
application.register('filepond', FilepondController)

import FilterController from './filter_controller'
application.register('filter', FilterController)

import FlashController from './flash_controller'
application.register('flash', FlashController)

import HelloController from './hello_controller'
application.register('hello', HelloController)

import InventoryController from './inventory_controller'
application.register('inventory', InventoryController)

import ObliterateController from './obliterate_controller'
application.register('obliterate', ObliterateController)

import OptionsController from './options_controller'
application.register('options', OptionsController)

import ReloadController from './reload_controller'
application.register('reload', ReloadController)

import SummernoteController from './summernote_controller'
application.register('summernote', SummernoteController)

import VariationController from './variation_controller'
application.register('variation', VariationController)